### PR TITLE
Solve problem with SSL certificates

### PR DESCRIPTION
**Pull request by bogem**
Before:

After:

### CODE REVIEW

**Comment by pawurb** [comment]
I do not want to include more dependencies. Skipping verification seems like the simplest way to fix it and I don't think it poses any security threat. 

As for alphapetical order please submit it as another PR.

**Comment by bogem** [comment]
How can I skip verification?

**Comment by bogem** [comment]
Your program doesn't work without SSL certificate on my computer :(

**Comment by pawurb** [comment]
A added the verification skipping in version "2.12.0" . Run `gem update termit` and let me know if the problem persists.

**Comment by bogem** [comment]
Same

**Comment by pawurb** [comment]
Released `2.12.1` with a possible fix. Let me know if it works. Hard to test it for me since I never encountered it before.

**Comment by bogem** [comment]
It works now👍
Thanks!

**Pull request closed without merging**
